name: Ghostbind CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Checkout over SSH using the key stored in CI_DEPLOY_KEY
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.CI_DEPLOY_KEY }}

      # 2️⃣  Python runtime
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣  Optional dependencies (ignored if requirements.txt absent)
      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then
            pip install -qr requirements.txt
          else
            echo "no requirements.txt — skipping pip install"
          fi

      # 4️⃣  Hinge self-test — no SSH needed, so no ssh-add here
      - name: Hinge self-test (DRY_RUN)
        env:
          GB_DRY_RUN: "1"
        run: |
          echo "Running hinge self-test ..."
          if [ -f hinge.py ]; then
            python hinge.py --selftest
          else
            echo "hinge.py not present — skipping."
          fi
